# Generated by Django 5.1.6 on 2025-02-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('img', models.ImageField(default='default.png', upload_to='uploads')),
                ('sale', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
            ],
        ),
    ]
