# Generated by Django 5.1.6 on 2025-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=1000)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('img', models.ImageField(default='default.png', upload_to='uploads')),
            ],
        ),
    ]
