# Generated by Django 5.1.6 on 2025-03-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_addcard_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcard',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addcard',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
