# Generated by Django 5.1.6 on 2025-03-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_address_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_upi', models.IntegerField(default=2)),
                ('upi', models.IntegerField(default=3)),
                ('shop_balance', models.IntegerField(default=2)),
                ('net_bank', models.IntegerField(default=3)),
                ('cash_on', models.IntegerField(default=7)),
                ('Free', models.IntegerField(default=0)),
                ('Oneday', models.IntegerField(default=79)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.IntegerField(default='00000000'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default='0000'),
        ),
    ]
