# Generated by Django 5.0.6 on 2025-06-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delivery_alter_address_phone_alter_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcard',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buy',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
